# Generated by Django 5.2.5 on 2025-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
